
accelerometer:
  iir_filter:
    enable: true
    # butterworth low-pass, 1st order, 1000 Hz sampling frequency, 10 Hz cutoff frequency
    a: [1.0, -0.9391]
    b: [0.0305, 0.0305]

  notch_filter:
    enable: true
    sample_rate: 1000 # [Hz]
    frequencies: [125, 250, 375] # [Hz]
    bandwidth: 100 # [Hz]

gyro:
  iir_filter:
    enable: true
    # butterworth low-pass, 1st order, 1000 Hz sampling frequency, 10 Hz cutoff frequency
    a: [1.0, -0.9391]
    b: [0.0305, 0.0305]

  notch_filter:
    enable: true
    sample_rate: 1000 # [Hz]
    frequencies: [125, 250, 375] # [Hz]
    bandwidth: 100 # [Hz]
