
accelerometer:
  iir_filter:
    enable: true
    # # butterworth low-pass, 1st order, 400 Hz sampling frequency, 10 Hz cutoff frequency
    a: [1.0, -0.8541]
    b: [0.073, 0.073]

  notch_filter:
    enable: true
    sample_rate: 400 # [Hz]
    frequencies: [100, 200] # [Hz]
    bandwidth: 100 # [Hz]

gyro:
  iir_filter:
    enable: true
    # # butterworth low-pass, 1st order, 400 Hz sampling frequency, 10 Hz cutoff frequency
    a: [1.0, -0.8541]
    b: [0.073, 0.073]

  notch_filter:
    enable: true
    sample_rate: 400 # [Hz]
    frequencies: [100, 200] # [Hz]
    bandwidth: 100 # [Hz]
